name: Bug Report
description: File a bug report.
title: "[Bug]: "
labels: ["bug"]
body:
  - type: textarea
    id: describe-bug
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce
      description: Step-by-step instructions to produce the unexpected behaviour.
    validations:
      required: true
  - type: textarea
    id: expected-behaviour
    attributes:
      label: Expected behaviour
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Crash log
      description: Copy and paste in any relevant crash logs in plain text.
      render: shell
  - type: dropdown
    id: pc-version
    attributes:
      label: What version of PlayCover are you using?
      options:
        - "3.0.0 beta 2"
        - "3.0.0 beta 1"
        - 2.0.5
        - 2.0.4
        - "Nightly/beta (please specify build number)"
        - "Other (please specify)"
    validations:
        required: true
  - type: dropdown
    id: mac-version
    attributes:
      label: What version of macOS are you using?
      options:
        - "Sonoma (macOS 14)"
        - "Ventura (macOS 13)"
        - "Monterey (macOS 12)"
        - "macOS beta (please state the specific version)"
        - "Other (please specify)"
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: Issue Language
      description: All issues must be written in clear plain English so that all devs are able to read them.
      options:
        - label: Yes my issue is written in English
          required: true
