name: SwiftLint

on:
  # Run on PR and push to every branch
  pull_request:
  push:
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  SwiftLint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      
      - name: SwiftLint
        uses: norio-nomura/action-swiftlint@3.2.1
        with:
          args: --strict
